"""add product variants and cart variant_id

Revision ID: 0286a764eab6
Revises: 07bff416f1c9
Create Date: 2026-05-05 18:49:39.793590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0286a764eab6'
down_revision = '07bff416f1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('unique_cart_item'), type_='unique')
        batch_op.create_unique_constraint('unique_cart_item', ['user_id', 'product_id', 'variant_id'])
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_cart_item', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_cart_item'), ['user_id', 'product_id'])
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
