"""add custom_price to cart

Revision ID: 07bff416f1c9
Revises: 551545ea69c6
Create Date: 2026-04-28 20:29:50.768151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bff416f1c9'
down_revision = '551545ea69c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('custom_price')

    # ### end Alembic commands ###
