"""add otp model and user verified field

Revision ID: 21271ec22db8
Revises: 2f747f3c8cb4
Create Date: 2026-03-20 20:17:36.264708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21271ec22db8'
down_revision = '2f747f3c8cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
