"""add cancel fields

Revision ID: 2f747f3c8cb4
Revises: 
Create Date: 2026-03-20 19:52:55.669198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f747f3c8cb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cancel_note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancel_flagged')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancel_note')
        batch_op.drop_column('cancel_reason')

    # ### end Alembic commands ###
