"""add recently_viewed table

Revision ID: c3f9027a090e
Revises: 0286a764eab6
Create Date: 2026-05-09 20:58:44.979499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f9027a090e'
down_revision = '0286a764eab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_cart_item'), type_='unique')
        batch_op.create_unique_constraint('unique_cart_item', ['user_id', 'product_id', 'variant_id'])
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('variant_label', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_label')
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_cart_item', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_cart_item'), ['user_id', 'product_id'])

    # ### end Alembic commands ###
