"""add coupon delivery zone

Revision ID: c92f13918218
Revises: 8f2f303de665
Create Date: 2026-03-21 18:06:03.440728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92f13918218'
down_revision = '8f2f303de665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_charge', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_charge')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('coupon_code')

    # ### end Alembic commands ###
