all_products = [
    {
        "id": 1,
        "name": "Cherry Tomato",
        "price": 100,
        "image": "/static/images/tomato.jpg",
        "description": "Fresh red tomato",
        "category": "Vegetables",
    },
    {
        "id": 2,
        "name": "Organic Juice",
        "price": 100,
        "image": "/static/images/juice.jpg",
        "description": "Fresh Organic Juice",
        "category": "Juices",
    },
    {
        "id": 3,
        "name": "Broccoli",
        "price": 120,
        "image": "/static/images/brocoli.jpg",
        "description": "Fresh broccoli",
        "category": "Vegetables",
    },
    {
        "id": 4,
        "name": "Quinoa",
        "price": 200,
        "image": "/static/images/quinoa.jpg",
        "description": "Healthy quinoa",
        "category": "Grains",
    },
    {
        "id": 5,
        "name": "Grapes",
        "price": 130,
        "image": "/static/images/grapes.jpg",
        "description": "Sweet grapes",
        "category": "Fruits",
    },
    {
        "id": 6,
        "name": "Oats",
        "price": 120,
        "image": "/static/images/oats.jpg",
        "description": "Organic oats",
        "category": "Grains",
    },
    {
        "id": 7,
        "name": "Cow Milk",
        "price": 60,
        "image": "/static/images/milk.jpg",
        "description": "Pure cow milk",
        "category": "Dairy",
    },
    {
        "id": 8,
        "name": "Organic Spice",
        "price": 60,
        "image": "/static/images/spice.jpg",
        "description": "Original Organic Spice",
        "category": "Spices",
    },
    {
        "id": 9,
        "name": "Avocado",
        "price": 60,
        "image": "/static/images/avocado.jpg",
        "description": "Fresh Avocado",
        "category": "Fruits",
    },
    {
        "id": 10,
        "name": "WelNuts",
        "price": 250,
        "image": "/static/images/nuts.jpg",
        "description": "Healthy Welnuts",
        "category": "Nuts & Seeds",
    },
    {
        "id": 11,
        "name": "Bread",
        "price": 120,
        "image": "/static/images/bread.jpg",
        "description": "Fresh Bread",
        "category": "Bakery",
    },
    {
        "id": 12,
        "name": "White Bread",
        "price": 120,
        "image": "/static/images/b1.jpg",
        "description": "Fresh White Bread",
        "category": "Bakery",
    },
    {
        "id": 13,
        "name": "Whole Wheat Bread",
        "price": 150,
        "image": "/static/images/b2.jpg",
        "description": "Healthy Whole Wheat Bread",
        "category": "Bakery",
    },
    {
        "id": 14,
        "name": "Multigrain Bread",
        "price": 199,
        "image": "/static/images/b3.jpg",
        "description": "Nutritious Multigrain Bread",
        "category": "Bakery",
    },
    {
        "id": 15,
        "name": "Pure Organic Juice",
        "price": 150,
        "image": "/static/images/organic.jpg",
        "description": "Pure Organic Juice",
        "category": "Juices",
    },
    {
        "id": 16,
        "name": "Fresh Orange Juice",
        "price": 130,
        "image": "/static/images/orange.jpg",
        "description": "Freshly Squeezed Orange Juice",
        "category": "Juices",
    },
    {
        "id": 17,
        "name": "Mixed Fruit Juice",
        "price": 170,
        "image": "/static/images/mix.jpg",
        "description": "Healthy Mixed Fruit Juice",
        "category": "Juices",
    },
    {
        "id": 18,
        "name": "Healthy Green Juice",
        "price": 180,
        "image": "/static/images/green.jpg",
        "description": "Detoxifying Green Juice",
        "category": "Juices",
    },
    {
        "id": 19,
        "name": "Almond",
        "price": 150,
        "image": "/static/images/almonds.jpg",
        "description": "Premium Almonds",
        "category": "Nuts & Seeds",
    },
    {
        "id": 20,
        "name": "Organic Chia Seeds",
        "price": 130,
        "image": "/static/images/chia.jpg",
        "description": "High-fiber Organic Chia Seeds",
        "category": "Nuts & Seeds",
    },
    {
        "id": 21,
        "name": "Organic Brown Rice",
        "price": 170,
        "image": "/static/images/brown_rice.jpg",
        "description": "Healthy Organic Brown Rice",
        "category": "Grains",
    },
    {
        "id": 22,
        "name": "Organic Jaggery Powder",
        "price": 180,
        "image": "/static/images/jaggary.jpg",
        "description": "Pure Jaggery Powder",
        "category": "Grains",
    },
    {
        "id": 23,
        "name": "More Oats",
        "price": 180,
        "image": "/static/images/oats.jpg",
        "description": "Organic Oats",
        "category": "Grains",
    },
    {
        "id": 24,
        "name": "Organic Baby Spinach",
        "price": 120,
        "image": "/static/images/spinach.jpg",
        "description": "Fresh Baby Spinach",
        "category": "Vegetables",
    },
    {
        "id": 25,
        "name": "Organic Apples",
        "price": 180,
        "image": "/static/images/apple.jpg",
        "description": "Fresh Organic Apples",
        "category": "Fruits",
    },
    {
        "id": 26,
        "name": "Organic Grapes",
        "price": 150,
        "image": "/static/images/grapes.jpg",
        "description": "Sweet Organic Grapes",
        "category": "Fruits",
    },
    {
        "id": 27,
        "name": "Whole Wheat Bread",
        "price": 150,
        "image": "/static/images/b2.jpg",
        "description": "Fresh Whole Wheat Bread",
        "category": "Bakery",
    },
    {
        "id": 28,
        "name": "Healthy Green Juice",
        "price": 180,
        "image": "/static/images/green.jpg",
        "description": "Organic Green Juice",
        "category": "Juices",
    },
    {
        "id": 29,
        "name": "Organic Brown Rice",
        "price": 150,
        "image": "/static/images/brown_rice.jpg",
        "description": "Organic Brown Rice",
        "category": "Grains",
    },
    {
        "id": 30,
        "name": "Bread",
        "price": 120,
        "image": "/static/images/bread.jpg",
        "description": "Fresh Bread",
        "category": "Bakery",
    },
    {
        "id": 31,
        "name": "Organic Granola Jar",
        "price": 410,
        "image": "/static/images/Granola Jar.jpg",
        "description": "Organic Granola Jar",
        "category": "Grains",
    },
    {
        "id": 32,
        "name": "Peas",
        "price": 120,
        "image": "/static/images/peas.jpg",
        "description": "Fresh Peas",
        "category": "Vegetables",
    },
    {
        "id": 33,
        "name": "Corn",
        "price": 320,
        "image": "/static/images/corn.jpg",
        "description": "Sweet Corn",
        "category": "Vegetables",
    },
    {
        "id": 34,
        "name": "Organic Peanut Butter",
        "price": 140,
        "image": "/static/images/peanut butter.jpg",
        "description": "Peanut Butter",
        "category": "Nuts & Seeds",
    },
    {
        "id": 35,
        "name": "Mix Juice",
        "price": 150,
        "image": "/static/images/j.jpg",
        "description": "Mixed Fruit Juice",
        "category": "Juices",
    },
    {
        "id": 36,
        "name": "Apple",
        "price": 120,
        "image": "/static/images/apple.jpg",
        "description": "Fresh Red Apple",
        "category": "Fruits",
    },
    {
        "id": 37,
        "name": "Grapes",
        "price": 90,
        "image": "/static/images/grapes.jpg",
        "description": "Fresh Grapes",
        "category": "Fruits",
    },
    {
        "id": 38,
        "name": "Banana",
        "price": 60,
        "image": "/static/images/banana.jpg",
        "description": "Organic Banana",
        "category": "Fruits",
    },
    {
        "id": 39,
        "name": "Orange",
        "price": 80,
        "image": "/static/images/orange1.jpg",
        "description": "Juicy Orange",
        "category": "Fruits",
    },
    {
        "id": 40,
        "name": "Mango",
        "price": 150,
        "image": "/static/images/mango.jpg",
        "description": "Sweet Mango",
        "category": "Fruits",
    },
    {
        "id": 41,
        "name": "Pineapple",
        "price": 70,
        "image": "/static/images/pineapple.jpg",
        "description": "Fresh Pineapple",
        "category": "Fruits",
    },
    {
        "id": 42,
        "name": "Strawberry",
        "price": 200,
        "image": "/static/images/strawberrie.jpg",
        "description": "Fresh Strawberry",
        "category": "Fruits",
    },
    {
        "id": 43,
        "name": "Kiwi",
        "price": 180,
        "image": "/static/images/kiwi.jpg",
        "description": "Healthy Kiwi",
        "category": "Fruits",
    },
    {
        "id": 44,
        "name": "Tomato",
        "price": 40,
        "image": "/static/images/tomato.jpg",
        "description": "Fresh Tomato",
        "category": "Vegetables",
    },
    {
        "id": 45,
        "name": "Broccoli",
        "price": 110,
        "image": "/static/images/brocoli.jpg",
        "description": "Green Broccoli",
        "category": "Vegetables",
    },
    {
        "id": 46,
        "name": "Carrot",
        "price": 50,
        "image": "/static/images/carrots.jpg",
        "description": "Organic Carrots",
        "category": "Vegetables",
    },
    {
        "id": 47,
        "name": "Spinach",
        "price": 30,
        "image": "/static/images/Spinach.jpg",
        "description": "Fresh Spinach",
        "category": "Vegetables",
    },
    {
        "id": 48,
        "name": "Lettuce",
        "price": 45,
        "image": "/static/images/lettuce.jpg",
        "description": "Green Lettuce",
        "category": "Vegetables",
    },
    {
        "id": 49,
        "name": "Bell Pepper",
        "price": 90,
        "image": "/static/images/bell-pepper.jpg",
        "description": "Fresh Bell Pepper",
        "category": "Vegetables",
    },
    {
        "id": 50,
        "name": "Cauliflower",
        "price": 60,
        "image": "/static/images/cauliflower.jpg",
        "description": "White Cauliflower",
        "category": "Vegetables",
    },
    {
        "id": 51,
        "name": "Cucumber",
        "price": 40,
        "image": "/static/images/cucumber.jpg",
        "description": "Fresh Cucumber",
        "category": "Vegetables",
    },
    {
        "id": 52,
        "name": "Milk",
        "price": 55,
        "image": "/static/images/milk.jpg",
        "description": "Fresh Milk",
        "category": "Dairy",
    },
    {
        "id": 53,
        "name": "Buffalo Milk",
        "price": 65,
        "image": "/static/images/buffelo.jpg",
        "description": "Buffalo Milk",
        "category": "Dairy",
    },
    {
        "id": 54,
        "name": "Cheese",
        "price": 220,
        "image": "/static/images/cheese.jpg",
        "description": "Fresh Cheese",
        "category": "Dairy",
    },
    {
        "id": 55,
        "name": "Paneer",
        "price": 260,
        "image": "/static/images/paneer.jpg",
        "description": "Fresh Paneer",
        "category": "Dairy",
    },
    {
        "id": 56,
        "name": "Butter",
        "price": 180,
        "image": "/static/images/butter.jpg",
        "description": "Creamy Butter",
        "category": "Dairy",
    },
    {
        "id": 57,
        "name": "Ghee",
        "price": 520,
        "image": "/static/images/ghee.jpg",
        "description": "Pure Cow Ghee",
        "category": "Dairy",
    },
    {
        "id": 58,
        "name": "Curd",
        "price": 50,
        "image": "/static/images/curd.jpg",
        "description": "Fresh Curd",
        "category": "Dairy",
    },
    {
        "id": 59,
        "name": "Eggs",
        "price": 70,
        "image": "/static/images/egg.jpg",
        "description": "Farm Fresh Eggs",
        "category": "Dairy",
    },
    {
        "id": 60,
        "name": "Orange Juice",
        "price": 90,
        "image": "/static/images/orange.jpg",
        "description": "Fresh Orange Juice",
        "category": "Juices",
    },
    {
        "id": 61,
        "name": "Apple Juice",
        "price": 100,
        "image": "/static/images/apple-juice.jpg",
        "description": "Fresh Apple Juice",
        "category": "Juices",
    },
    {
        "id": 62,
        "name": "Coconut Water",
        "price": 45,
        "image": "/static/images/coconut.jpg",
        "description": "Fresh Coconut Water",
        "category": "Beverages",
    },
    {
        "id": 63,
        "name": "Coffee",
        "price": 180,
        "image": "/static/images/coffee.jpg",
        "description": "Premium Coffee",
        "category": "Beverages",
    },
    {
        "id": 64,
        "name": "Tea",
        "price": 160,
        "image": "/static/images/tea.jpg",
        "description": "Refreshing Tea",
        "category": "Beverages",
    },
    {
        "id": 65,
        "name": "Lemon Juice",
        "price": 35,
        "image": "/static/images/leamon.jpg",
        "description": "Fresh Lemon Juice",
        "category": "Juices",
    },
    {
        "id": 66,
        "name": "Soft Drink",
        "price": 60,
        "image": "/static/images/drink.jpg",
        "description": "Cold Soft Drink",
        "category": "Beverages",
    },
    {
        "id": 67,
        "name": "Green Tea",
        "price": 200,
        "image": "/static/images/green.jpg",
        "description": "Healthy Green Tea",
        "category": "Beverages",
    },
    {
        "id": 68,
        "name": "Almonds",
        "price": 650,
        "image": "/static/images/almonds.jpg",
        "description": "Premium Almonds",
        "category": "Nuts & Seeds",
    },
    {
        "id": 69,
        "name": "Cashew Nuts",
        "price": 720,
        "image": "/static/images/cashew.jpg",
        "description": "Fresh Cashews",
        "category": "Nuts & Seeds",
    },
    {
        "id": 70,
        "name": "Mixed Nuts",
        "price": 600,
        "image": "/static/images/nuts.jpg",
        "description": "Healthy Mixed Nuts",
        "category": "Nuts & Seeds",
    },
    {
        "id": 71,
        "name": "Peanuts",
        "price": 120,
        "image": "/static/images/peanut.jpg",
        "description": "Fresh Peanuts",
        "category": "Nuts & Seeds",
    },
    {
        "id": 72,
        "name": "Pistachios",
        "price": 780,
        "image": "/static/images/pistachios.jpg",
        "description": "Premium Pistachios",
        "category": "Nuts & Seeds",
    },
    {
        "id": 73,
        "name": "Raisins",
        "price": 320,
        "image": "/static/images/raisins.jpg",
        "description": "Sweet Raisins",
        "category": "Nuts & Seeds",
    },
    {
        "id": 74,
        "name": "Chia Seeds",
        "price": 280,
        "image": "/static/images/chia.jpg",
        "description": "Healthy Chia Seeds",
        "category": "Nuts & Seeds",
    },
    {
        "id": 75,
        "name": "Flax Seeds",
        "price": 200,
        "image": "/static/images/flax.jpg",
        "description": "Organic Flax Seeds",
        "category": "Nuts & Seeds",
    },
    {
        "id": 76,
        "name": "Oats",
        "price": 180,
        "image": "/static/images/oats.jpg",
        "description": "Healthy Oats",
        "category": "Grains",
    },
    {
        "id": 77,
        "name": "Quinoa",
        "price": 350,
        "image": "/static/images/quinoa.jpg",
        "description": "Premium Quinoa",
        "category": "Grains",
    },
    {
        "id": 78,
        "name": "Red Chili Powder",
        "price": 150,
        "image": "/static/images/redchilli.jpg",
        "description": "Organic Red Chilli Powder",
        "category": "Spices",
    },
    {
        "id": 79,
        "name": "Turmeric Powder",
        "price": 170,
        "image": "/static/images/termeric.jpg",
        "description": "Organic Turmeric Powder",
        "category": "Spices",
    },
    {
        "id": 80,
        "name": "Cumin Seeds",
        "price": 190,
        "image": "/static/images/cumin.jpg",
        "description": "Organic Cumin Seeds",
        "category": "Spices",
    },
    {
        "id": 81,
        "name": "Black Pepper",
        "price": 210,
        "image": "/static/images/black-pepper.jpg",
        "description": "Organic Black Pepper",
        "category": "Spices",
    },
    {
        "id": 82,
        "name": "Salted Chips",
        "price": 90,
        "image": "/static/images/potato-chips.jpg",
        "description": "Salted Chips",
        "category": "Snacks",
    },
    {
        "id": 83,
        "name": "Cookies",
        "price": 110,
        "image": "/static/images/cookies.jpg",
        "description": "Healthy Oats Cookies",
        "category": "Snacks",
    },
    {
        "id": 84,
        "name": "Frozen French Fries",
        "price": 80,
        "image": "/static/images/french-fries.jpg",
        "description": "Crispy Frozen French Fries",
        "category": "Frozen",
    },
    {
        "id": 85,
        "name": "Frozen Veg Momos",
        "price": 70,
        "image": "/static/images/momos.jpg",
        "description": "Frozen Vegetable Momos",
        "category": "Frozen",
    },
    {
        "id": 86,
        "name": "Frozen Green Juice Cube",
        "price": 90,
        "image": "/static/images/natural.jpg",
        "description": "Healthy Green Juice Cubes",
        "category": "Frozen",
    },
    {
        "id": 87,
        "name": "Frozen Ginger Cube",
        "price": 150,
        "image": "/static/images/ginger-cube.jpg",
        "description": "Organic Ginger Cubes",
        "category": "Frozen",
    },
    {
        "id": 88,
        "name": "Frozen Potato Wedges",
        "price": 50,
        "image": "/static/images/wedges.jpg",
        "description": "Spicy Potato Wedges",
        "category": "Frozen",
    },
    {
        "id": 89,
        "name": "Frozen Blueberry",
        "price": 150,
        "image": "/static/images/blueberry.jpg",
        "description": "Fresh Frozen Blueberries",
        "category": "Frozen",
    },
    {
        "id": 90,
        "name": "Organic Aloe Vera Gel",
        "price": 120,
        "image": "/static/images/gel.jpg",
        "description": "Natural Aloe Vera Gel for Skin & Hair",
        "category": "Personal Care",
    },
    {
        "id": 91,
        "name": "Herbal Shampoo",
        "price": 180,
        "image": "/static/images/shampoo.jpg",
        "description": "Chemical-Free Herbal Shampoo",
        "category": "Personal Care",
    },
    {
        "id": 92,
        "name": "Organic Body Lotion",
        "price": 200,
        "image": "/static/images/lotion.jpg",
        "description": "Moisturizing Organic Body Lotion",
        "category": "Personal Care",
    },
    {
        "id": 93,
        "name": "Organic Face Wash",
        "price": 150,
        "image": "/static/images/wash.jpg",
        "description": "Gentle Organic Face Cleanser",
        "category": "Personal Care",
    },
    {
        "id": 94,
        "name": "Cold Pressed Coconut Oil",
        "price": 250,
        "image": "/static/images/coconut-oil.jpg",
        "description": "Pure Cold Pressed Coconut Oil",
        "category": "Personal Care",
    },
]